### ISSUE TITLE
ESP32 reboots after bad command

### ISSUE THREAD

**Issue by HazardCreative** [ryaniftron/clearview_interface_public#22] opened 2020-05-09 22:59 UTC
To reproduce:

1. Boot ESP32 and connect to MQTT server
2. Start a RotorHazard server

ESP log below appears, followed by normal boot sequence.

```
I (53825) PUBLISH_TEST: MQTT_EVENT_DATA
Xdname: 'CV_40'TOPIC=rx/cv1/cmd_all
DATA=
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400d7367  PS      : 0x00060730  A0      : 0x800d77aa  A1      : 0x3ffcaf90
0x400d7367: process_mqtt_message at c:\users\hazard\documents\github\clearview_interface_public\src\cvesp32\build/../main/main_cv_mqtt.c:347

A2      : 0x3ffbfd68  A3      : 0x0000000e  A4      : 0x3ffc8680  A5      : 0x00000000
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x800d7363  A9      : 0x3ffcaf40
A10     : 0x00000007  A11     : 0x3ffcb1bc  A12     : 0x00000000  A13     : 0x0000000c
A14     : 0x00000000  A15     : 0x3ffc1ab0  SAR     : 0x00000004  EXCCAUSE: 0x0000001d
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff

ELF file SHA256: e06f920c9bf36fc422f3367390b82ca00f66eddae3b8b9b4466cfc30783d864b

Backtrace: 0x400d7364:0x3ffcaf90 0x400d77a7:0x3ffcafe0 0x400d7ea6:0x3ffcb000 0x400d81ff:0x3ffcb020 0x400d832f:0x3ffcb060 0x400d8604:0x3ffcb090 0x4008d7a5:0x3ffcb0c0
0x400d7364: process_mqtt_message at c:\users\hazard\documents\github\clearview_interface_public\src\cvesp32\build/../main/main_cv_mqtt.c:347

0x400d77a7: mqtt_event_handler at c:\users\hazard\documents\github\clearview_interface_public\src\cvesp32\build/../main/main_cv_mqtt.c:545 (discriminator 9)

0x400d7ea6: esp_mqtt_dispatch_event at D:/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:623

0x400d81ff: deliver_publish at D:/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:671 (discriminator 4)

0x400d832f: mqtt_process_receive at D:/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:924

0x400d8604: esp_mqtt_task at D:/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:1066

0x4008d7a5: vPortTaskWrapper at D:/esp-idf/components/freertos/port.c:143


Rebooting...
```

**Comment by ryaniftron** [comment] 2020-05-10 03:49
From initial tests, this seems to be caused by something on the ESP32's RX buffer. Without hooking up a ClearView, the issue is not present. Due to an exception error not letting all the debug messages through, although it looks like failing during the UART TX, it could be on the return parsing. 

On my unit, the message received is a request from the RH for lock status of all the connected devices.

**Comment by ryaniftron** [comment] 2020-05-10 23:46
When testing with a ClearView, I was not able to reproduce the error. The only command sent is ODD to turn off the OSD when the server starts up. This does not ask for a reply from the CV, so there is nothing in the RX buffer to get handled improperly. Perhaps you aren't running the latest ESP32 code?

**Comment by HazardCreative** [comment] 2020-05-11 00:29
I'll update. But does the ESP reboot after any bad command? It should ignore malformed commands, not fail and reboot.

**Comment by ryaniftron** [comment] 2020-05-11 01:15
No, the ESP takes the payload from a command and sends it directly to the CV. If the CV responds to a report request, the ESP packages up the response (whatever it is) and ships it back to RH.

All the checking for malformatted commands and responses occurs in the python code. Thus, I am not clear what would cause a reboot other than some overflow or memory access issue. I'll keep an eye on it though.

**Comment by ryaniftron** [comment] 2020-05-13 22:53
Closing because there does not appear to be this bug anymore.

**Closed as completed by ryaniftron** 2020-05-13 22:53 UTC
Labels: bug, ESP32
